name: Go

on:
  push:
    branches: [ main ]
    tags:
      - "[0-9].[0-9].[0-9]"
  pull_request:
    branches: [ main ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
# test
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.X

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - if: github.ref == 'refs/heads/main'
      name: Deploy
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          CloudBeesDemo

    - if: contains(github.ref, "refs/tags/[0-9].[0-9].[0-9]")
      name: Deploy
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${GITHUB_REF}"
        files: |
          CloudBeesDemo

